### ISSUE TITLE
read_b2_output( b2fgmtry ) includes timesa key, which doesn't belong in this file

### ISSUE THREAD

**Issue by eldond** [ProjectTorreyPines/SOLPS2IMAS.jl#3]
In `test/runtests.jl`:
`contents = read_b2_output("$(@__DIR__)/../samples/b2fgmtry")`
returns a structure that contains "timesa" within "data", but "timesa" is a b2time.nc thing; it shouldn't be found in b2fgmtry

**Comment by anchal-physics** [comment]
That was intentional on my end. Edge_profiles.grid_ggd is supposed to be an array of structures corresponding to a time evolution. This time is stored in edge_profiles.grid_ggd[:].time . For consistency with any future implementation of time dependent grids, I introduced a timestamp 0.0 for the grid while storing it from b2fgmtry. Let me know if you still think we should remove it.

**Comment by eldond** [comment]
That might be overdoing it on future compatibility, but okay, we can leave it for now if you think it's a good idea.
